import type { NextPage } from "next";
import Head from "next/head";
import Dashboard from "../components/Dashboard";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://line.me/R/ti/p/%40444rlonw">USAOMOCHI!</a>
        </h1>
        <Dashboard />
      </main>
    </div>
  );
};

export default Home;
